import { lazy } from 'react'

export const VIBES = [
  {
    id: 'wmp',
    label: '2000s',
    icon: '💿',
    color: '#0078d4',
    description: 'Windows Media Player nostalgia. Aurora trails and frequency rings.',
    Scene:    lazy(() => import('./wmp/Scene')),
    PlayerUI: lazy(() => import('./wmp/PlayerUI')),
  },
  {
    id: 'winamp',
    label: '90s',
    icon: '🖥️',
    color: '#00ff00',
    description: 'Classic Winamp skin. Pixel-perfect retro UI with a spinning CD.',
    Scene:    lazy(() => import('./winamp/Scene')),
    PlayerUI: lazy(() => import('./winamp/PlayerUI')),
  },
  {
    id: 'flowery',
    label: 'FLOWERY',
    icon: '🌸',
    color: '#ff88bb',
    description: 'Petals bloom and drift with every beat. Soft and dreamy.',
    Scene:    lazy(() => import('./flowery/Scene')),
    PlayerUI: lazy(() => import('./flowery/PlayerUI')),
  },
  {
    id: 'chill',
    label: 'CHILL',
    icon: '🌊',
    color: '#00aaff',
    description: 'Ocean bubbles and caustic light. Smooth tunes, deep vibes.',
    Scene:    lazy(() => import('./chill/Scene')),
    PlayerUI: lazy(() => import('./chill/PlayerUI')),
  },
  {
    id: 'hype',
    label: 'HYPE',
    icon: '⚡',
    color: '#ff00ff',
    description: 'Neon tunnels and electric bursts. Turn it up.',
    Scene:    lazy(() => import('./hype/Scene')),
    PlayerUI: lazy(() => import('./hype/PlayerUI')),
  },
  {
    id: 'cosmic',
    label: 'COSMIC',
    icon: '🪐',
    color: '#aa66ff',
    description: 'Stars, nebulae, and orbiting rings. Float through the universe.',
    Scene:    lazy(() => import('./cosmic/Scene')),
    PlayerUI: lazy(() => import('./cosmic/PlayerUI')),
  },
  {
    id: 'sad',
    label: 'RAIN',
    icon: '🌧️',
    color: '#4a88b8',
    description: 'Raindrops and ripples. For when the weather matches the mood.',
    Scene:    lazy(() => import('./sad/Scene')),
    PlayerUI: lazy(() => import('./sad/PlayerUI')),
  },
  {
    id: 'focus',
    label: 'FOCUS',
    icon: '🎯',
    color: '#cccccc',
    description: 'Minimal geometry, breathing orb. Deep work mode.',
    Scene:    lazy(() => import('./focus/Scene')),
    PlayerUI: lazy(() => import('./focus/PlayerUI')),
  },
  {
    id: 'cassette',
    label: 'CASSETTE',
    icon: '📼',
    color: '#c89018',
    description: 'Retro tape deck with spinning reels. Old school never dies.',
    Scene:    lazy(() => import('./cassette/Scene')),
    PlayerUI: lazy(() => import('./cassette/PlayerUI')),
  },
]

export const DEFAULT_VIBE = 'winamp'
